In [1]:
import pandas as pd

In [3]:
bd_weather = pd.DataFrame({
    "city": ["dhaka", "khulna", "sylhet"],
    "tem": [35, 32, 30],
    "humidity": [80, 60, 78],
})

bd_weather

     city  tem  humidity
0   dhaka   35        80
1  khulna   32        60
2  sylhet   30        78

In [4]:
us_weather = pd.DataFrame({
    "city": ["new york", "florida", "chicago"],
    "tem": [25, 22, 20],
    "humidity": [60, 40, 58],
})

us_weather

       city  tem  humidity
0  new york   25        60
1   florida   22        40
2   chicago   20        58

In [6]:
# vertical merge
df = pd.concat([bd_weather, us_weather])
df

       city  tem  humidity
0     dhaka   35        80
1    khulna   32        60
2    sylhet   30        78
0  new york   25        60
1   florida   22        40
2   chicago   20        58

In [7]:
df = pd.concat([bd_weather, us_weather], ignore_index=True)
df

       city  tem  humidity
0     dhaka   35        80
1    khulna   32        60
2    sylhet   30        78
3  new york   25        60
4   florida   22        40
5   chicago   20        58

In [9]:
df = pd.concat([bd_weather, us_weather], keys=["bangladesh", "us"])
df

                  city  tem  humidity
bangladesh 0     dhaka   35        80
           1    khulna   32        60
           2    sylhet   30        78
us         0  new york   25        60
           1   florida   22        40
           2   chicago   20        58

In [10]:
# get the us cities
df.loc["us"]

       city  tem  humidity
0  new york   25        60
1   florida   22        40
2   chicago   20        58

In [16]:
tem_df = pd.DataFrame({
    "city": ["dhaka", "khulna", "sylhet"],
    "tem": [35, 32, 30],
})

wind_df = pd.DataFrame({
    "city": ["dhaka", "khulna", "sylhet"],
    "wind": [55, 72, 90],
})

print(tem_df)

     city  tem
0   dhaka   35
1  khulna   32
2  sylhet   30

In [18]:
pd.concat([tem_df, wind_df], axis=1)

     city  tem    city  wind
0   dhaka   35   dhaka    55
1  khulna   32  khulna    72
2  sylhet   30  sylhet    90

In [20]:
# Merge
tem_df = pd.DataFrame({
    "city": ["dhaka", "khulna", "sylhet"],
    "tem": [35, 32, 30],
})

wind_df = pd.DataFrame({
    "city": ["dhaka", "khulna", "sylhet"],
    "wind": [55, 72, 90],
})

print(wind_df)

     city  wind
0   dhaka    55
1  khulna    72
2  sylhet    90

In [21]:
pd.merge(tem_df, wind_df, on="city")

     city  tem  wind
0   dhaka   35    55
1  khulna   32    72
2  sylhet   30    90

In [28]:
# Merge
tem_df = pd.DataFrame({
    "city": ["dhaka", "khulna", "chittagong", "rajshahi"],
    "tem": [35, 32, 30, 45],
})

wind_df = pd.DataFrame({
    "city": ["dhaka", "khulna", "sylhet"],
    "wind": [55, 72, 90],
})

print(wind_df)

     city  wind
0   dhaka    55
1  khulna    72
2  sylhet    90

In [29]:
pd.merge(tem_df, wind_df, on="city", how='outer') # how=inner/right/left/outer

         city   tem  wind
0  chittagong  30.0   NaN
1       dhaka  35.0  55.0
2      khulna  32.0  72.0
3    rajshahi  45.0   NaN
4      sylhet   NaN  90.0