In [13]:
import pandas as pd

df = pd.read_csv("movies.csv")
df.head(2) #data frame

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English

In [8]:
df.tail(2)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [9]:
df.sample(4) # random

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.0,1046.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.5,263.1,Millions,USD,English

In [10]:
df.shape

(37, 10)

In [14]:
df.imdb_rating.min(), df.imdb_rating.max(), df.imdb_rating.mean()

(np.float64(1.9), np.float64(9.3), np.float64(7.919444444444445))

In [20]:
df_b = df[df.industry=="Bollywood"]
df_h = df[df.industry=="Hollywood"]
df_h.loc[[df_h.imdb_rating.idxmax()]] # value of hightest rating hollywood movie

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [21]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [22]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [23]:
df.language.unique()

array(['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu'], dtype=object)

In [24]:
df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [15]:
df_new = df[["title", "industry", "imdb_rating"]]
df_new

                                          title   industry  imdb_rating
0                               Pather Panchali  Bollywood          8.3
1   Doctor Strange in the Multiverse of Madness  Hollywood          7.0
2                         Thor: The Dark World   Hollywood          6.8
3                               Thor: Ragnarok   Hollywood          7.9
4                       Thor: Love and Thunder   Hollywood          6.8
5                      The Shawshank Redemption  Hollywood          9.3
6                                  Interstellar  Hollywood          8.6
7                      The Pursuit of Happyness  Hollywood          8.0
8                                     Gladiator  Hollywood          8.5
9                                       Titanic  Hollywood          7.9
10                        It's a Wonderful Life  Hollywood          8.6
11                                       Avatar  Hollywood          7.8
12                                The Godfather  Hollywood          9.2
13                              The Dark Knight  Hollywood          9.0
14                             Schindler's List  Hollywood          9.0
15                                Jurassic Park  Hollywood          8.2
16                                     Parasite  Hollywood          8.5
17                            Avengers: Endgame  Hollywood          8.4
18                       Avengers: Infinity War  Hollywood          8.4
19           Captain America: The First Avenger  Hollywood          6.9
20          Captain America: The Winter Soldier  Hollywood          7.8
21                  Dilwale Dulhania Le Jayenge  Bollywood          8.0
22                                     3 Idiots  Bollywood          8.4
23                     Kabhi Khushi Kabhie Gham  Bollywood          7.4
24                             Bajirao Mastani   Bollywood          7.2
25                             Taare Zameen Par  Bollywood          8.3
26                          Munna Bhai M.B.B.S.  Bollywood          8.1
27                                           PK  Bollywood          8.1
28                                        Sanju  Bollywood          NaN
29                            The Kashmir Files  Bollywood          8.3
30                            Bajrangi Bhaijaan  Bollywood          8.1
31                                       Race 3  Bollywood          1.9
32                                    Shershaah  Bollywood          8.4
33                             K.G.F: Chapter 2  Bollywood          8.4
34                    Pushpa: The Rise - Part 1  Bollywood          7.6
35                                          RRR  Bollywood          8.0
36                     Baahubali: The Beginning  Bollywood          8.0

In [30]:
# print movies from 2000-2010
df[(df.release_year >= 2000) & (df.release_year <= 2010)]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [32]:
df[df.studio=="Marvel Studios"]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [33]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [35]:
#Print highest and lowest rating movies
df[(df.imdb_rating == df.imdb_rating.max()) | (df.imdb_rating == df.imdb_rating.min())]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [38]:
# Add a new column of how old the movie is from 2026
df["age"] = df["release_year"].apply(lambda x: 2026 - x)
df.sample(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,11
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,25
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,80
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,11
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,15

In [56]:
# add new column of profit, revenue - budget
# 1. Drop existing 'profit' column if present
if "profit" in df.columns:
    df.drop(columns=["profit"], inplace=True)

# 2. Calculate profit
profit_data = df["revenue"] - df["budget"]

# 3. Get location of 'unit'
unit_idx = df.columns.get_loc("unit")

# 4. Insert 'profit' before 'unit'
df.insert(unit_idx, "profit", profit_data)

df.sample(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,profit,unit,currency,language,age
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,7690.0,Millions,INR,Hindi,12
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.0,2202.0,2002.0,Millions,USD,English,29
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,6.5,Billions,INR,Telugu,4
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,1230.0,Millions,INR,Hindi,19
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,2398.0,Millions,USD,English,7

In [8]:
# set title as index
df.set_index("title", inplace=True)

KeyError: "None of ['title'] are in the columns"

In [6]:
df.head(3)

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
title,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English

In [7]:
df.index

Index(['Pather Panchali', 'Doctor Strange in the Multiverse of Madness',
       'Thor: The Dark World ', 'Thor: Ragnarok ', 'Thor: Love and Thunder ',
       'The Shawshank Redemption', 'Interstellar', 'The Pursuit of Happyness',
       'Gladiator', 'Titanic', 'It's a Wonderful Life', 'Avatar',
       'The Godfather', 'The Dark Knight', 'Schindler's List', 'Jurassic Park',
       'Parasite', 'Avengers: Endgame', 'Avengers: Infinity War',
       'Captain America: The First Avenger',
       'Captain America: The Winter Soldier', 'Dilwale Dulhania Le Jayenge',
       '3 Idiots', 'Kabhi Khushi Kabhie Gham', 'Bajirao Mastani ',
       'Taare Zameen Par', 'Munna Bhai M.B.B.S.', 'PK', 'Sanju',
       'The Kashmir Files', 'Bajrangi Bhaijaan', 'Race 3', 'Shershaah',
       'K.G.F: Chapter 2', 'Pushpa: The Rise - Part 1', 'RRR',
       'Baahubali: The Beginning'],
      dtype='object', name='title')

In [9]:
df.loc["Taare Zameen Par"]

industry        Bollywood
release_year         2007
imdb_rating           8.3
studio                NaN
budget              120.0
revenue            1350.0
unit             Millions
currency              INR
language            Hindi
Name: Taare Zameen Par, dtype: object

In [11]:
df.iloc[5]

industry                        Hollywood
release_year                         1994
imdb_rating                           9.3
studio          Castle Rock Entertainment
budget                               25.0
revenue                              73.3
unit                             Millions
currency                              USD
language                          English
Name: The Shawshank Redemption, dtype: object