In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("stock_data.csv")
df
# header are not showing properly for extra line

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [4]:
df = pd.read_csv("stock_data.csv", skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [6]:
# Change header names
df = pd.read_csv("stock_data.csv", header=1, names=["Stock_symbol", "EPS", "Revenue", "Price", "People"])
df

  Stock_symbol            EPS  Revenue Price         People
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [10]:
df = pd.read_csv("stock_data.csv", header=1, nrows=4)
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65           n.a.
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani

In [14]:
# Transform Garbage values
df = pd.read_csv("stock_data.csv", header=1, na_values=['n.a.', -1, 'not available'])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [15]:
df["pe"] = df["price"]/df["eps"]
df

  tickers    eps  revenue   price         people         pe
0   GOOGL  27.82     87.0   845.0     larry page  30.373832
1     WMT   4.61    484.0    65.0            NaN  14.099783
2    MSFT    NaN     85.0    64.0     bill gates        NaN
3    RIL     NaN     50.0  1023.0  mukesh ambani        NaN
4    TATA   5.60      NaN     NaN     ratan tata        NaN

In [18]:
# export new csv
df.to_csv("pe_edited1.csv", index=False)