In [1]:
import pandas as pd

In [5]:
df_movies = pd.read_excel("movies_db.xlsx", "movies")
df_movies.head(2)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5

In [6]:
df_financials = pd.read_excel("movies_db.xlsx", "financials")
df_financials.head(2)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD

In [14]:
dfs = pd.read_excel("movies_db.xlsx", sheet_name=["actors", "movie_actor", "languages"])
df_actor = dfs["actors"]
df_movie_actor = dfs["movie_actor"]
df_languages = dfs["languages"]
df_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [15]:
# convert $$, Dollars to USD
def convert_curr(curr):
    if curr == "$$" or curr == "Dollars":
        return "USD"
    return curr

df_financials = pd.read_excel("movies_db.xlsx", "financials", converters = {
    "currency": convert_curr
})
df_financials.head(10)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD
5       107   400.0   2000.0  Millions      INR
6       108   550.0   4000.0  Millions      INR
7       109   390.0   1360.0  Millions      INR
8       110     1.4      3.5  Billions      INR
9       111    25.0     73.3  Millions      USD

In [16]:
df_financials["currency"].unique()

array(['INR', 'USD'], dtype=object)

# Merge Movies and Financials report based on movie_id

In [18]:
df_merged = pd.merge(df_movies, df_financials, on="movie_id")
df_merged.head(2)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD

In [21]:
# Export to new xlxs file
df_merged.to_excel("movie_finance_merged.xlsx")